.TH SECRET 1

.SH NAME
secret \- encrypts and transfers file over a secure channel

.SH SYNOPSIS
secret -r <file> -s <ip|hostname> [-l]

.SH DESCRIPTION
Client/server application, which file over a secure channel, where data is transfered inside ICMP Echo-Request/Response messages. File is encrypted before transferring to not be transferred in plain-text.

.SH OPTIONS
.TP
.BR \-r " " <file>
File to be transferred
.TP
.BR \-s " " \<ip|hostname\>
IP address/hostname where to send the file
.TP
.BR \-l
Program should be run as server, which listens to incoming ICMP messages and saves received file to same directory as it had been executed
