.TH SECRET 1

.SH NAME
secret \- encrypts and transfers file over a secure channel using only ICMP echo request messages

.SH SYNOPSIS
secret -r <file> -s <ip|hostname> [-l]

.SH DESCRIPTION
Client/server application, which file over a secure channel, where data is transfered inside ICMP Echo-Request/Response messages. File is encrypted using AES 128 block cypher before transferring to not be transferred in plain-text. Application supports transfer over IPv4 as well as IPv6.

.SH OPTIONS
.TP
.BR \-r " " <file>
File to be transferred
.TP
.BR \-s " " \<ip|hostname\>
IP address/hostname where to send the file
.TP
.BR \-l
Program should be run as server, which listens to incoming ICMP messages and saves received file to same directory as it had been executed
.TP
.BR \-v
Verbose, log debug info to stdout
.TP
.BR \-h
Print help

.SH EXAMPLES
.TP
sudo ./secret -s ::1 -r test/test1.txt
Transfer test/test1.txt file to server listening on IPv6 loopback
.TP 
sudo ./secret -l
Start server to listen to incoming files
.SH AUTHOR
.TP 
Samuel Oleksak (xoleks00)